name: Generate Certification Documents

on:
  workflow_dispatch:

jobs:
  generate-cert-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

     - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install openai==1.3.8 httpx==0.24.1
  
      - name: Unzip uploaded file
        run: |
          mkdir -p input_zip
          unzip '*.zip' -d input_zip || echo "No ZIP file uploaded"

      - name: Run document generation script
        run: |
          python scripts/process_zip_and_generate.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Upload generated documentation
        uses: actions/upload-artifact@v4
        with:
          name: cert_packageV1
          path: cert_packageV1/
